### ISSUE TITLE
ImportError: No module named pretrainedmodels.models.torchvision_models

### ISSUE THREAD

**Issue by KleinXin** [qubvel/segmentation_models.pytorch#11]
File "/home/Disk0/SMP/segmentation_models_pytorch/encoders/resnet.py", line 4, in <module>
    from pretrainedmodels.models.torchvision_models import pretrained_settings

Where are the pretrainedmodels？

thx

**Comment by KleinXin** [comment]
solved by installing pretrainedmodels

**Comment by agiokas-dbg** [comment]
I just got that error.
For clarity I'm including my solution (because the answer above doesn't really explain what to do):

`pip install pretrainedmodels` is an external dependency on this repo: https://github.com/IvyGongoogle/pretrained-models.pytorch

This gets you another error:

`ModuleNotFoundError: No module named 'efficientnet_pytorch'`

Then type:
`pip install efficientnet-pytorch` which is yet another dependency from: https://github.com/lukemelas/EfficientNet-PyTorch

At this point you can use this repository getting rid of those errors.

**Comment by qubvel** [comment]
Look at `requirements.txt` to install correct dependencies
