### ISSUE TITLE
RuntimeError: Expected 4-dimensional input for 4-dimensional weight 64 3 7 7 139708288704784, but got 5-dimensional input of size [8, 4, 3, 256, 256] instead

### ISSUE THREAD

**Issue by ninjakx** [qubvel/segmentation_models.pytorch#111]
How to train when you are having stacked images (brain mri modes : t1, t1c, t2, flair) ?.
My input shape is (8, 4, 3, 256, 256) where 
batch-size = 8
no of stacked images = 4
channel = 3(rgb)
width = 256
height = 256

**Comment by Geeks-Sid** [comment]
PepeHands, The problem is right now, the repo only support 2D images. I think if you want to do 3D images, you can't use this. 
If you want a work around, convert the 3D-stack to slices and then you might have:

((8*4):3:256:256) image stack which you can use to train, but be aware of choosing slices.
