### ISSUE TITLE
The length and width of the input picture cannot be arbitrary?

### ISSUE THREAD

**Issue by ancy397031272** [qubvel/segmentation_models.pytorch#165]

**Comment by SinclairHudson** [comment]
For this repo, yes. I found that experimenting with efficientnet-b0, both my image dimensions had to be divisible by 32. This is because of the downsampling and upsampling operations; they need to divide with no remainder. Any remainder will be ignored and you'll end up with a dimension mismatch if you have any skip connections. Try multiples of powers of two, since downsampling is often done with 2x2 pooling.
