### ISSUE TITLE
Prediction(test) sample ??

### ISSUE THREAD

**Issue by edwardcho** [qubvel/segmentation_models.pytorch#185]
Hello Sir.

I got models using your code.
Now I want to predict for my-test images using only trained-model.
(This is no validation, this is prediction).

(My input is as follows, 1. trained-model, 2. image_filepath)

Thanks....

**Comment by edwardcho** [comment]
Hello Sir.

I tested prediction-code of yours.

```python
    # Predictions
    for i in range(5):
        n = np.random.choice(len(test_dataset))

        image = test_dataset[n]

        x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
        pr_mask = loaded_model.predict(x_tensor)
        pr_mask = (pr_mask.squeeze().cpu().numpy().round())

        print(pr_mask)
```

But I met some error.
```python
Traceback (most recent call last):
  File "inference_rev1.py", line 423, in <module>
    in_model_weights=args.model_weights)
  File "inference_rev1.py", line 162, in submit
    in_model_weights=in_model_weights)
  File "inference_rev1.py", line 391, in inferences
    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
TypeError: expected np.ndarray (got tuple)
```

Thanks..

**Comment by edwardcho** [comment]
Hello Sir....

I had tried prediction process.
(input : image_path) But I don't know inference way...

```python
    image_path = '/data/TESTBOARD/additional_networks/segmentation/Amazing-Semantic-Segmentation_luyanger1799_keras/DPA/test/images/waa067;1________=a11410__3_15_24.png'
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = loaded_model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
```
If you can, please tell me...

Thanks..

**Comment by edwardcho** [comment]
Hello Sir,

I had tried prediction process....
(input : image_path)...

```python
    image_dir = '/data/test/images'
    image_filename_1 = 'test123.png'
    image_filename_2 = 'test234.png'
    image_path = os.path.join(image_dir, image_filename_2)
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    preprocessing_fn_inference = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)
    preprocessing_inference=get_preprocessing(preprocessing_fn_inference)

    sample = preprocessing_inference(image=image, mask=None)
    image = sample['image']

    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = loaded_model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
```

Is it correct??

Thanks...

**Comment by edwardcho** [comment]
Hello Sir,

I met another problems.

Count of class of my-data is 17. 
When inference my code, I got (17, 256, 256) for pr_mask.

If so, How to visualize result for my-data??

Thanks..

**Comment by adeschemps** [comment]
First issue (21 April) is that you are feeding a tuple (an immutable datastructure containing a pair of values) where this code is expecting a numpy array. That's because an element of the dataset is a tuple of numpy array with a mask and a ground truth image. You need to select only the image in this tuple, by doing something like image[0], or image, mask = input_dataset[n]. 

Second issue (23 april) is because the network returns a one-hot encoded tensor. To convert it to a 1 channel image, you can do predicted_mask = np.argmax(predicted_mask, axis = 0) (on the first axis because Pytorch uses a channels-first representation). This will convert it to a 1 channel image. You will need to transpose the array to set the channel last for plotting. 

That's a bit late but I hope this is helpful !
