### ISSUE TITLE
How to visualize my result of multi-class training?

### ISSUE THREAD

**Issue by edwardcho** [qubvel/segmentation_models.pytorch#188]
Hello Sir,

I tried train and got model.
(count of class of my-data is 17.)

Then, my inference code is as follows.
```python
    image_dir = '/data/test/images'
    image_filename_2 = 'test234.png'
    image_path = os.path.join(image_dir, image_filename_2)
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    preprocessing_fn_inference = smp.encoders.get_preprocessing_fn(ENCODER, ENCODER_WEIGHTS)
    preprocessing_inference=get_preprocessing(preprocessing_fn_inference)

    sample = preprocessing_inference(image=image, mask=None)
    image = sample['image']

    x_tensor = torch.from_numpy(image).to(DEVICE).unsqueeze(0)
    pr_mask = loaded_model.predict(x_tensor)
    pr_mask = (pr_mask.squeeze().cpu().numpy().round())
```

I got pr_mask, shape of pr_mask is (17, 256, 256).

I don't know how to visualize the result for my data.

Thanks..

**Comment by howard-mahe** [comment]
Hello @edwardcho, at this stage you have one heat maps for each your class but you have not decided yet which label to predict for a given pixel. If only one label must be predicted for a given pixel, then you must take the `np.argmax` of `pr_mask` to obtain a label in range `[0..16]` for each pixel.

At this point, you can visualize your predictions but you will barely see anything because all the values are concentrated in the bottom part of the `[0..255]` range. Either you map your values from `[0..16]` to `[0..255]` by doing `pr_mask = (pr_mask.astype('float') * 255.0/16).astype('uint8')` or you apply a custom colormap to your predictions in order to colorize it:
```python
# define colormap
cmap = np.zeros((17,), dtype=np.uint8)
cmap[0] = [0, 121, 177]
cmap[1] = [170, 200, 230]
...
cmap[16] = [255, 124, 40]

# apply colormap
colored_pred = cmap[pr_mask]
```

**Comment by edwardcho** [comment]
Hello Sir.

Yes, I could find my result with your help.

pred = pr_mask(axis=0)   # I could get (256x256) of best label.

Thanks.
