### ISSUE TITLE
Best way to increase the number of feature layers of the encoder?

### ISSUE THREAD

**Issue by JulienMaille** [qubvel/segmentation_models.pytorch#222]
I'd like to try to increase a 4-layers resnet18 from 64/64/128/256 to maybe 128/128/128/256 because I feel I have a lot of information at full resolution.
Of course i'd like to keep the pretrained weight for the first 64 feature layers.
Something similar to the "hack" you have implemented to allow input with more than 3 channels.
Would you have any idea on the best way to do this?
Thanks

**Comment by Geeks-Sid** [comment]
How would that be a pretrained network? Do you mean number of filters in encoder? Do you not want to use imagenet pretrained?

**Comment by JulienMaille** [comment]
Yes I'm talking about the filters layers (3,64,64,128,256) for a small resnet. This could be increased to (3,128,128,256,512) while keeping the imagenet weight, what do you think?

**Comment by Geeks-Sid** [comment]
I'm sorry to say but that's not possible. Not only is this feature unavailable, you might need to use a different network because you cannot use imagenet weights on networks with random shape. Please feel free to use a bigger network.

**Comment by JulienMaille** [comment]
well, qubvel implemented a way to have something else than the 3-channel RGB input (you can have more or less channels), so why would this be impossible for the next layer?

**Comment by Geeks-Sid** [comment]
That is just for changing the input channel.
Also, I have no idea how you plan to load imagenet weights into a different network because the networks will change automatically if you change anything with the number of filters.

Qubvel has provided support for having multi channel input, you can have 1 channel image or 3 channel image or 30 channel image, but you cannot change the network. You can try changing number of filters in decoder though, but I am sure you cannot change number of filters in encoder.

**Comment by JulienMaille** [comment]
Understood, thanks for your insights
