### ISSUE TITLE
ModuleNotFoundError: No module named 'segmentation_models_pytorch.losses'

### ISSUE THREAD

**Issue by XinlingQiu** [qubvel/segmentation_models.pytorch#361]
Hello! Thanks so much for your work! When I want to use the losses here, there is a error:ModuleNotFoundError: No module named 'segmentation_models_pytorch.losses'. Would you help me to solve this problem? Thank you very much!

**Comment by DhruvAwasthi** [comment]
Can you please share the gist where you are getting this error?

**Comment by Nachimak28** [comment]
Try uninstalling the library and instead of installing using pypi, try doing a pip from source installation as follows:
`pip install git+https://github.com/qubvel/segmentation_models.pytorch`
I tried this in two separate conda environments, one with the pypi based installation and in another one by using the latest version from source. 
The later one solves the issue. 

There seem to be massive differences in the release version and the main branch on github where losses have moved to the `segmentation_models.pytorch/segmentation_models_pytorch/losses` although probably the old Jaccard and Dice loss are still present `segmentation_models.pytorch/segmentation_models_pytorch/utils/losses.py ` file incase you're interested using them but its better to use the latest loss functions.

**Comment by RedMoon32** [comment]
Same error, can I create a PR to fix it?

**Comment by ghltshubh** [comment]
Didn't work for me.

**Comment by nikheelpandey** [comment]
what's the fix here?

**Comment by aishstha** [comment]
> 

you need to us version of library which contains focal loss. Preferably latest sm version.
