### ISSUE TITLE
module 'segmentation_models_pytorch' has no attribute 'utils'

### ISSUE THREAD

**Issue by ymzlygw** [qubvel/segmentation_models.pytorch#624]
Hey, I install the latest version of smp. But When I use:  

    metrics = [
        smp.utils.metrics.IoU(threshold=0.5),
    ]
 I get the error:   

    module 'segmentation_models_pytorch' has no attribute 'utils'  

Could you please tell me why this happend?

**Comment by Shima-shoki** [comment]
Hi, maybe your question is similar to mine I asked days ago, and the discussion is in the closed issues :)
https://github.com/qubvel/segmentation_models.pytorch/issues/619#issue-1322329467
The utils module is not found in the 'segmentation_models_pytorch' module from the most recent version (0.3.0) since [qubvel](https://github.com/qubvel) is considering to remove it, but you can still download it by 

```
import segmentation_models_pytorch.utils
```

Hope this helps you!

**Comment by ymzlygw** [comment]
> Hi, maybe your question is similar to mine I asked days ago, and the discussion is in the closed issues :) [#619 (comment)](https://github.com/qubvel/segmentation_models.pytorch/issues/619#issue-1322329467) The utils module is not found in the 'segmentation_models_pytorch' module from the most recent version (0.3.0) since [qubvel](https://github.com/qubvel) is considering to remove it, but you can still download it by
> 
> ```
> import segmentation_models_pytorch.utils
> ```
> 
> or
> 
> ```
> from segmentation_models_pytorch import utils
> ```
> 
> Hope this helps you!

Thanks for that! I will close the issue.
