### ISSUE TITLE
Mix Vision Transformer encoder KeyError

### ISSUE THREAD

**Issue by mattiagatti** [qubvel/segmentation_models.pytorch#685]
Hello,

when I define a model by specifying "mit_b5" (or any other model of the Mix Vision Transformer family) I get a KeyError.

For example:
`model = smp.Unet(
    encoder_name='mit_b5',
    encoder_weights='imagenet',
    in_channels=3,
    classes=1,
    activation=None
)`
Throws me a KeyError.

Thank you!

**Comment by CozyDoomer** [comment]
I also get 
`KeyError: "wrong encoder name mit_b2, supported encoders: [...]`
when installing the package from pypi or git.

The only way I got Mix Vision Transformer to work was installing from source:
`git clone https://github.com/qubvel/segmentation_models.pytorch.git`
`cd segmentation_models.pytorch`
`pip install .`

which is weird because AFAIK
`pip install git+https://github.com/qubvel/segmentation_models.pytorch` should do the same
